# conda env create -n <env_name> --file <this_file>.yml
# sudo conda-env create -n new_od_env --file _backup_environment.yml
# To activate this environment, use
#
#     $ conda activate new_od_env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

#pip install asyncio --upgrade
#pip install ipykernel --upgrade

channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - jupyter
  - matplotlib
  - notebook
  - numpy=1.19
  - opencv=4.5
  - pandas=1.1
  - pip
  - pyqt=5.12
  - pytest=6.1
  - python=3.9
  - supervisely=6.1.59
  - pip:
    - awscli==1.18.180
    - chardet==3.0.4
    - click==7.1.2
    - flake8==3.8.4
    - python-dotenv==0.15.0
    - pyyaml==5.3.1
    - sphinx==3.3.1
